### ISSUE TITLE
Cannot read property 'aurelia' of null

### ISSUE THREAD

**Issue by obany** [aurelia/protractor-plugin#13]
**I'm submitting a bug report**

* **Library Version:**
1.0.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.1.2

* **NPM Version:**
5.0.3

* **Browser:**
Chrome 59

* **Language:**
all

**Current behavior:**

I have a custom bootstrap behaviour for my Aurelia App and so the aurelia-app attribute is not immediately available when the page loads. This causes the loadAndWaitForAureliaPage to trigger a 
Cannot read property 'aurelia' of null
because the document.querySelector("[aurelia-app]") returns null. 

**Expected/desired behavior:**
Should safely check the attribute before accessing the .aurelia property.

PR for the fix here https://github.com/aurelia/protractor-plugin/pull/12

**Comment by niieani** [comment]
Closed by #12.

**Comment by niieani** [comment]
Thanks!
