### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jp7677** [aurelia/protractor-plugin#16]
Hi there,
With latest official aurelia dependencies I'm hitting the following error:
`Cannot read property 'aurelia' of null`
Seems this has already been fixed on master.

Could you please consider to release a new version of aurelia-protractor-plugin?

**Comment by jp7677** [comment]
Ping?

**Comment by EisenbergEffect** [comment]
On it! This must have somehow slipped off the list. We'll get it out in the next couple of days. Apologies!

**Comment by jp7677** [comment]
No problem, Thanks a lot!
