### ISSUE TITLE
by.binding for Aurelia

### ISSUE THREAD

**Issue by lmj0011** [aurelia/protractor-plugin#3]
Question.

is by.binding supported for Aurelia
http://www.protractortest.org/#/api?view=ProtractorBy.prototype.binding

**Comment by lmj0011** [comment]
not supported, the error message you get when trying to use `by.binding`

```sh
Failed: unknown error: angular is not defined
(Session info: chrome=55.0.2883.87) 
(Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-57-generic x86_64)
```

**Comment by EisenbergEffect** [comment]
We have some custom helpers in our starter kits. They have to be built specifically for Aurelia.

**Comment by lmj0011** [comment]
>We have some custom helpers in our starter kits

I would like to view these, where are the starter kits located?

**Comment by EisenbergEffect** [comment]
I apologize. You'll have to excuse me. I wasn't thinking clearly when I responded earlier. We did move the code out of the starter kits into this repository. So, if you wanted to have that functionality for Aurelia, you could submit a PR to the index.js file in this repo.
