### ISSUE TITLE
Timeout when using plugin with aurelia-cli

### ISSUE THREAD

**Issue by th3mon** [aurelia/protractor-plugin#5]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.3

* **Node Version:**
7.4.0

* **NPM Version:**
4.0.5

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I use aurelia-cli. I done config for the Protractor, installed a plugin for aurelia. 
I've always got the same timeout error. I figured out that in **loadAndWaitForAureliaPage()** is condition which checks presence of **webpackJsonp**. I don't use webpack, so I deleted that condition and it started working well!
Why the presence of webpack is being verified?

**Expected/desired behavior:**

I've done [fork](https://github.com/th3mon/protractor-plugin/commit/66f34753a844a7ae10161198a010e6a89abaf627) for short time maintenance.

* **What is the expected behavior?**
Plugin should work for all type of module bundlers, loaders and so on tools, not only for webpack.

* **What is the motivation / use case for changing the behavior?**
It would be nice to have a plugin which cooperates with aurelia-cli.

**Comment by EisenbergEffect** [comment]
@niieani Can you take a look at this? It is possible that something was changed here which isn't friendly to non-webpack setups?

**Comment by niieani** [comment]
I'll have a look at this while finalizing the skeleton PR.

**Comment by abrahamq** [comment]
Any update on this? I'm having the same problems trying to test my code. Thanks!

**Comment by niieani** [comment]
This was fixed a while ago.
