### ISSUE TITLE
browser.executeScript doesn't take a callback

### ISSUE THREAD

**Issue by jonabc** [aurelia/protractor-plugin#6]
**I'm submitting a bug report**

* **Library Version:**
1.0.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
7.9.0

* **NPM Version:**
4.2.0

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
Running e2e tests from aurelia-skeleton skeleton-esnext-webpack project result in the following
![screen shot 2017-04-23 at 12 27 38 am](https://cloud.githubusercontent.com/assets/5263772/25311653/be89baa4-27bb-11e7-9a06-d3cd4fdce5d8.png)

**Expected/desired behavior:**
1. Clone [aurelia-skeleton](https://github.com/aurelia/skeleton-navigation) and use skeleton-esnext-webpack
2. At time of writing there are two minor blockers that need to be fixed to continue

* update package.json for invalid babel-loader "next" tag
```
"devDependencies": {
...
  "babel-loader": "^7.0.0"
...
}
```
* update .babelrc.js for invalid "useBuiltIns": true (I think the correct option now is "usage")
```
"presets": [
...
        "useBuiltIns": "usage"
...
]
```

3. npm install
4. npm start -- e2e

* **What is the expected behavior?**
browser.executeScript should not cause an exception

* **What is the motivation / use case for changing the behavior?**
With the change from `browser.executeAsyncScript` to `browser.executeScript` in #4 , it appears that a callback is not available.
Locally reverting #4 so that `executeAsyncScript` is used fixes the issue.  I don't know the motivation behind using `executeScript` so I'm hesitant to create the change in a PR.

**Comment by niieani** [comment]
Hey, thanks for the report. Indeed, I investigated the same problem and I'm working on a solution. For now, feel free to use version 1.0.1.
