### ISSUE TITLE
Forcing Browser refresh between tests breaks all but first test.

### ISSUE THREAD

**Issue by TomFoyster** [aurelia/protractor-plugin#7]
**I'm submitting a bug report**

* **Library Version:**
3.0.0

* **Operating System:**
Windows 7

* **Node Version:**
6.10.1

* **NPM Version:**
3.10.10

* **Browser:**
N/A

* **Language:**
ESNext

**Current behavior:**
Adding the ` restartBrowserBetweenTests: true,` parameter into _protractor.conf.js_ causes all but the first test to fail with the following errors;

> Failed: browser.loadAndWaitForAureliaPage is not a function

>  Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or use your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"

**Expected/desired behavior:**
The tests run independently of each other, without issue. 

* **What is the motivation / use case for changing the behavior?**
Some tests don't seem to work when the same instance of `browser` is used - so refreshing the browser between tests is required. 

Full config;
```

// An example configuration file.
exports.config = {
  directConnect: true,

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  restartBrowserBetweenTests: true,

  // optional: add seleniumServerJar with proper version number
  // seleniumServerJar: './node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.53.1.jar',
  specs: ['test/e2e/dist/**/*.js'],

  plugins: [{
    package: 'aurelia-protractor-plugin'
  }],


  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000
  }
};

```

**Comment by EisenbergEffect** [comment]
@zewa666 @niieani @jdanyow  Know anything about this setting?

**Comment by TomFoyster** [comment]
Can I ask why this was closed without an answer?

**Comment by zewa666** [comment]
@TomFoyster this was closed due to an commit https://github.com/aurelia/protractor-plugin/commit/63d8c71e0f7bb7ba16306c3ba45beff82ef4f52c. Are you still experiencing any issues?

**Comment by niieani** [comment]
@TomFoyster I've fixed the problem and tested it in the described conditions. It works properly now.

**Comment by jaas88** [comment]
I am experiencing this issue. `Failed: browser.loadAndWaitForAureliaPage is not a function` with "aurelia-protractor-plugin": "^1.0.6", and aurelia 0.33.1.

Any help?

Thanks.

**Comment by zewa666** [comment]
Can you describe your setup and maybe show the protractor.conf.js file?
