### ISSUE TITLE
Update @types/selenium-webdriver

### ISSUE THREAD

**Issue by michaelbull** [aurelia/protractor-plugin#8]
**I'm submitting a feature request**

* **Library Version:**
1.0.3

**Current behavior:**
The dependency on `@types/selenium-webdriver` is defined as any version with a major number of 2, however the latest version of `@types/selenium-webdriver` is 3.0.4.

**Expected/desired behavior:**

* **What is the expected behavior?**
The dependency on `@types/selenium-webdriver` should be updated to support the latest releases.

* **What is the motivation / use case for changing the behavior?**
Facilitating usage of the latest type definitions for the `selenium-webdriver` package.

**Comment by niieani** [comment]
PRs welcome :)

**Comment by michaelbull** [comment]
Good point, not sure why I didn't think of it given such a simple change. Done #9.
